app:
  host: localhost
  port: 4000
  proxy:
    # 若 HTTP Proxy Headers 可信，则可设置 `proxy` 为 `true`。
    false
  secret: null
  session:
    key: moment
  authorization-code: ""

query:
  complexity-limit: 65535

redis:
  host: localhost
  port: 6379
  password: null

postgresql:
  host: localhost
  port: 5432
  username: dayprimer
  password: pa$$w0rd
  database: dayprimer
